Solvik/netbox-agent

README.md
netbox_agent/ethtool.py
netbox_agent/network.py
netbox_agent/server.py
requirements.txt

handle network cards

---

netbox_agent/cli.py
netbox_agent/network.py
netbox_agent/server.py

Device update

---

README.md
netbox_agent/dell/dell.py
netbox_agent/hp/hp.py
netbox_agent/server.py

Change blade slot behavior

---

README.md
netbox_agent.yaml.example
netbox_agent/config.py
netbox_agent/ipmi.py
netbox_agent/location.py
netbox_agent/network.py
netbox_agent/server.py

Rework all network part

---

README.md
netbox_agent/config.py
netbox_agent/ipmi.py
netbox_agent/network.py

Fixes comments from #21 when I closed the MR a minute before @ramnes posted his review

Fix late comments

---

netbox_agent/server.py

I don't know why but I didn't commit this with PR #12 
Reopening #11

create server/rack/chassis with Rack location if found

---

netbox_agent/dell/dell.py
requirements.txt

I should really put more effort in committing tests..

More fixes

---

netbox_agent/dmidecode.py
netbox_agent/hp/hp.py

support HPE BL460c Gen10 and its stupid dmidecode info

---

README.md
netbox_agent.yaml.example
netbox_agent/config.py
netbox_agent/lldp.py
netbox_agent/network.py

Add LLDP auto cabling

---

netbox_agent/network.py

Handle IPv6 addresses

---

netbox_agent.yaml.example
netbox_agent/config.py
netbox_agent/location.py
netbox_agent/vendors/supermicro.py

Supermicro server can guess their slot via the config file

---

netbox_agent/inventory.py
netbox_agent/network.py
netbox_agent/vendors/supermicro.py

raid_array check should return an empty array, not NoneType
not all systems will have IPv6 defined, so try to get the information..  if not
just continue on.
Vendor Supermicro was incomplete.

Several minor fixes

---

netbox_agent/lldp.py
netbox_agent/network.py

Handle anycast IP

---

netbox_agent/cli.py
netbox_agent/config.py
netbox_agent/dmidecode.py
netbox_agent/inventory.py
netbox_agent/location.py
netbox_agent/logging.py
netbox_agent/network.py
netbox_agent/server.py
requirements.txt

new config system

---

netbox_agent/cli.py
netbox_agent/config.py
netbox_agent/network.py
netbox_agent/power.py
netbox_agent/server.py
netbox_agent/vendors/dell.py

Add power supply support

---

netbox_agent/inventory.py
netbox_agent/lshw.py
netbox_agent/misc.py
netbox_agent/network.py
netbox_agent/raid/hp.py
netbox_agent/raid/storcli.py
netbox_agent/server.py
netbox_agent/vendors/supermicro.py

Creates sata and nvme disk, motherboard, network interfaces, dimm's.
Since the difference between update and create is minimal, I've combined them together into a single function.  update gets empty arrays, which simply bypass the delete function and go straight to the create part of the update function.
Several duplicate code blocks was merged into a single function.
I have no idea if the raid still works.
You need to have the 'nvme' program installed, along with 'lshw' to use.
t

use lshw for inventory

---

netbox_agent/lldp.py
netbox_agent/network.py

handle multiple vlans in lldp

---

netbox_agent/inventory.py

make InventoryItem's name attribute <50 char for memory DIMM

---

netbox_agent/inventory.py
netbox_agent/misc.py
netbox_agent/raid/omreport.py

add omreport support

---

netbox_agent/inventory.py

Replace all special characters in slug with a dash rather than just spaces and dots

Replace all special characters in slug with a dash rather than just spaces and dots

---

netbox_agent/server.py

better error handling when DeviceRole or DeviceType don't exist

---

netbox_agent/server.py

The update function does stack dump.. This gets the chassis serial number.

Gets the right chassis serial number

---

netbox_agent/network.py

This remove fixed constants in network.py, and changes it to work by asking netbox what the values are.
v2.7 change many items from a constant, to a slug.

Use choices api

---

netbox_agent/cli.py
netbox_agent/vendors/generic.py
tests/fixtures/dmidecode/unknown.txt
tests/server.py

Adds a generic vendor for unrecognizable systems

Adds a generic vendor for unrecognizable systems

---

netbox_agent/lshw.py

Simply check that information for the CPU is available if there is a socket.

handle sockets with no cpu installed.  should fix #117

---

netbox_agent/ethtool.py

Fix this state:
```
root@xxx-3:~# ethtool -m eno1
Offset		Values
------		------
root@xxx-3:~#
```

fix ethtool class in case ethtool works but returns nothing

---

README.md
netbox_agent/cli.py
netbox_agent/config.py
netbox_agent/inventory.py
netbox_agent/ipmi.py
netbox_agent/logging.py
netbox_agent/misc.py
netbox_agent/network.py
netbox_agent/server.py
netbox_agent/virtualmachine.py

Virtual Machine feature 

---

netbox_agent/network.py

handle netbox 2.8 deprecation of _choices method

---

netbox_agent/network.py

Hi @Solvik,
I'm trying to continue the deployment of netbox-agent and updating it by the way where you know maybe :)
Will push some fix like this while I progress and try to bring feature if I got ideas :)
Regards,

Some fixes that prevent crash on register new a server

---

README.md

Better usage infos

---

netbox_agent/lshw.py

* Loop on nvme disk
* Remove vendor and product (not present, make crash)
* Use firmware version for version

LSHW nvme bugfix

---

netbox_agent/server.py

make the agent work if only a datacenter is specified

---

netbox_agent/server.py

fix agent crash on server creation if not blade

---

README.md
netbox_agent/vendors/hp.py
tests/fixtures/dmidecode/HP_ProLiant_m710x
tests/server.py

Hi,
I add the support of hp moonshot 1500 with ProLiant m750, m710x and m750 server cartridge.
I take the decison after digging a lot to declare that a moonshot is like a "blade".
(little linting btw)
Hope this help,
Regards,

Add HP Moonshot 1500 support

---

netbox_agent/vendors/supermicro.py

See should fix next travis jobs

Fix travis in supermicro

---

README.md
netbox_agent/inventory.py
netbox_agent/lshw.py

This add the inventory of display / gpu.

Add GPU inventory support

---

README.md
netbox_agent/server.py
netbox_agent/vendors/dell.py
netbox_agent/vendors/generic.py
netbox_agent/vendors/hp.py
netbox_agent/vendors/supermicro.py
tests/fixtures/dmidecode/HP_ProLiant_BL460c_Gen10_Graphics_Exp
tests/server.py

This add ProLiant BL460c Gen10 Graphics Exp support, blade server that got a GPU bay in the next slot 
To be merge after or same time as https://github.com/Solvik/netbox-agent/pull/164

Add "ProLiant BL460c Gen10 Graphics Exp" support and GPU expansion bay

---

netbox_agent/lldp.py

I got several time the case where there was a lldp problem in my network and was a little blind. This should help.

Check if lldpctl present, and log debug if no lldpctl output.

---

netbox_agent/vendors/supermicro.py
tests/server.py

fix ugly supermicro blade support

---

netbox_agent/virtualmachine.py

feat: add QEMU support

---

netbox_agent/raid/hp.py

...when matching only returncode 1
improv #218

fix: hp raid, prevent us to miss some errors

---

netbox_agent/misc.py

See https://stackoverflow.com/a/64106589/13596284

Fix module platform has no attribute linux_distribution

---

netbox_agent/server.py

A swag at fixing https://github.com/Solvik/netbox-agent/issues/230

Use platform id instead of record

---

netbox_agent/ipmi.py
netbox_agent/network.py

For the IPMI interface, I set the MTU per default to 1500.

feat: Retrieve and manage MTU for the interfaces

---

netbox_agent/virtualmachine.py

Simplify some of the logic in the `is_vm` function.

Simplify `is_vm` function

---

.gitignore
README.md
netbox_agent/cli.py
netbox_agent/network.py
netbox_agent/server.py
requirements.txt

Support Netbox 3

---

netbox_agent/inventory.py

`getattr` does not work on dict
Also add some rounding

Fix disk size inventory

---

netbox_agent/lshw.py

Improve resilience of several functions. Tested on my laptop.

Make lshw scrpping more resilient

---

netbox_agent/vendors/supermicro.py

Solution provided by @Garfunkl (Simon Brandstetter).
See details of the problem and solution in: https://github.com/Solvik/netbox-agent/issues/296

Workaround for Supermicro default serial number

---

netbox_agent/cli.py

int/bool confusion caused the exit code to be inverted

Fix exit code

---

netbox_agent/virtualmachine.py

Disk space was missing from the virtual machines properties

Set total disk space on VMs

---

netbox_agent/network.py

Fixes:
* Don't set duplex mode if virtual machine

Network interfaces
