- netbox_agent/network.py
An `IP` has an interface, not a device
Must have messed up while merge the device update PR
> hotfix - assign interface to ip while updating server

- netbox_agent/lshw.py
Fix
```
DEBUG:urllib3.connectionpool:https://netbox:443 "GET /api/dcim/manufacturers/?name=HP HTTP/1.1" 200 155
{'description': 'DIMM DDR3 Synchronous Registered (Buffered) 1333 MHz (0.8 ns)',
'id': 'bank:0',
'product': None,
'serial': 'N/A',
'size': 8.0,
'slot': 'PROC  1 DIMM  1',
'vendor': 'HP'}
DEBUG:urllib3.connectionpool:https://netbox:443 "POST /api/dcim/inventory-items/ HTTP/1.1" 400 43
File "/usr/bin/netbox_agent", line 11, in <module>
load_entry_point('netbox-agent==0.6.0', 'console_scripts', 'netbox_agent')()
File "/opt/venvs/netbox-agent/lib/python3.6/site-packages/netbox_agent/cli.py", line 44, in main
File "/opt/venvs/netbox-agent/lib/python3.6/site-packages/netbox_agent/cli.py", line 39, in run …
```
> Add missing N/A fallback on DIMM memory

- netbox_agent/network.py
Prevent crash due to unsupported mac format "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00" for a physical interface.
```
tun0       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
inet addr:10.10.0.2  P-t-P:10.10.0.1  Mask:255.255.255.255
inet6 addr: fe80::909:ce5:bb8d:1c46/64 Scope:Link
UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:13000  Metric:1
RX packets:175558389 errors:0 dropped:0 overruns:0 frame:0
TX packets:1436009662 errors:0 dropped:122828 overruns:0 carrier:0
collisions:0 txqueuelen:100 
RX bytes:29344700802 (29.3 GB)  TX bytes:1330509519768 (1.3 TB)
```
> Add openvpn TUN and TAP interfaces support, change type to Virtual and remove mac address

- netbox_agent/virtualmachine.py
Just digging more into the code. Saw a small change that I could add. Tested and works.
```
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.
17 structures occupying 1162 bytes.
Table at 0xBFFFFB70.
Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
Vendor: SeaBIOS
Version: 1.9.1-5.el7_3.2
Release Date: 04/01/2014
Address: 0xE8000
Runtime Size: 96 kB
ROM Size: 64 kB
Characteristics:
BIOS characteristics not supported
Targeted content distribution is supported
BIOS Revision: 0.0
Handle 0x0100, DMI type 1, 27 bytes
System Information
Manufacturer: Red Hat
Product Name: RHEV Hypervisor
Version: 7.3-1.1.el7
Serial Number: e5226058-9c7e-45ca-a90a-2a721ab1e269
UUID: 9a048ba4-e7e9-44d4-851e-0a6abd6aca20
Wake-up Type: Power Switch
SKU Number: Not Specified
Family: Red Hat Enterprise Linux
```
> small fix to add recognition of RHEV- Virtual machines

- README.md
- netbox_agent.yaml.example
- netbox_agent/config.py
Adding the --no_ssl_verify option to support Netbox connection with https and untrusted certificates
Usage example to allow connecting to netbox using self-signed certificates:
```
netbox_agent -c nbagent.yaml --register --no_ssl_verify
```
Usage exaample to allow connecting to netbox using https or ip:
```
netbox_agent -c nbagent.yaml --register
```
> Adding the --netbox.ssl_verify option

- netbox_agent/power.py
If you have a setup when one of the power supplies is in passive mode, you may get an error from the API:
DEBUG:urllib3.connectionpool:https://netbox.domain.com:443 "PATCH /api/dcim/power-ports/16/ HTTP/1.1" 400 71
File "/opt/rh/rh-python36/root/usr/bin/netbox_agent", line 11, in <module>
sys.exit(main())
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netbox_agent/cli.py", line 44, in main
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netbox_agent/cli.py", line 39, in run
server.netbox_create_or_update(config)
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netbox_agent/server.py", line 301, in netbox_create_or_update
self.power.report_power_consumption()
File …
> fix allocated_draw for inactive PSU

- netbox_agent/inventory.py
Example: Hi1710 [iBMC Intelligent Management system chip w/VGA support]
This product is too long, the api want max_length = 50 ...
> Truncate GPU product name to 50 characteres.

- netbox_agent/lshw.py
When nvme binary absent or too old and no json output, this crash the inventory, i prefer just pass nvme inventory and continue
> Fix inventory crash on nvme binary too old or absent

- netbox_agent/vendors/supermicro.py
This allows handling TwinPro Supermicro servers (e.g. `SYS-1028TP-DC1R`)
> Add support for Supermicro TwinPro devices

- README.md
Invalid character that causes some errors to throw if you're copying and pasting the config
> Remove an invalid character

- netbox_agent/lshw.py
Hi @Solvik,
I hope you are well.
The inventory crash with default nvme-cli version 1.8.1 on Centos7.
This fix it.
Best regards,
> NVME inventory fix.

- netbox_agent/lldp.py
- netbox_agent/server.py
In some case, i miss id and this make crash the agent, i'm not sure its the ideal solution but this first the crash and I can register my device.
```
File "/usr/bin/netbox_agent", line 33, in <module>
sys.exit(load_entry_point('netbox-agent==0.6.2', 'console_scripts', 'netbox_agent')())
File "/opt/venvs/netbox-agent/lib/python3.6/site-packages/netbox_agent/cli.py", line 44, in main
File "/opt/venvs/netbox-agent/lib/python3.6/site-packages/netbox_agent/cli.py", line 39, in run
server.netbox_create_or_update(config)
File "/opt/venvs/netbox-agent/lib/python3.6/site-packages/netbox_agent/server.py", line 391, in netbox_create_or_update
ret, server = self.update_netbox_location(server)
File …
```
> Fix a crash when missing rack id

- netbox_agent/config.py
- netbox_agent/inventory.py
- netbox_agent/raid/base.py
- netbox_agent/raid/hp.py
- netbox_agent/server.py
- netbox_agent/vendors/hp.py
This patch adds an option to clear remaining devices in the context of a new device replacing an old one with the same name but with a different hardware.
The serial leading to the bug is described below:
- A first server is registered under name `A` with serial `X`
- A second server is registered under name `B` with serial `Y`
- The server with serial `X` is decomissionned, but not removed
- The server with serial `Y` is reinstalled with name `A`
In this case, a device with serial `X` is well found, and netbox agent tries to update its name. But this raises an error because of the unique constraint on name, as another device already holds this name.
The proposed solution to handle this situation is to delete any device with same `name` but different `serial` before handling a device.
As …
> Added option to purge remaining devices

- netbox_agent/config.py
- netbox_agent/inventory.py
- netbox_agent/raid/base.py
- netbox_agent/raid/hp.py
- netbox_agent/server.py
- netbox_agent/vendors/hp.py
This patch adds the ability to detect and manage GPU and Disk expansion bays, and either add their internal components into the device corresponding to the blade server, or into a dedicated device.
It takes advantage of the work made by @cyrinux on GPU bays management, and applies the same principle to the external disk bays, but harmonize the inventory management:
- If no argument is specified on the command line, the GPU cards, RAID controllers and their attached disks are added in the blade device, and the device corresponding to an expansion device is deleted.
- If the `--expansion-as-device` option is specified on the command line, a dedicated device corresponding to the expansion bay is created, and the GPUs, RAID card and attached disks are removed from the blade device and added …
> Manage blade expansions as independent devices

- README.md
- netbox_agent.yaml.example
- netbox_agent/config.py
- netbox_agent/server.py
Hi,
This option add the support of custom fields. 
```bash
$ netbox_agent -du --device.custom_fields="last_run=$(date),last_run_ts=$(date +'%s')"
```
obviously, custom_fields need to be create manually in netbox admin
> feat: add custom_fields support

- README.md
- netbox_agent/config.py
- netbox_agent/inventory.py
- netbox_agent/lshw.py
- netbox_agent/misc.py
- netbox_agent/network.py
- netbox_agent/power.py
- netbox_agent/raid/hp.py
- netbox_agent/raid/omreport.py
- netbox_agent/raid/storcli.py
- netbox_agent/server.py
- netbox_agent/vendors/generic.py
This patch brings some of the physical and virtual drive attributes as `custom_fields` to the disks inventory.
The goal is to have this information present to ease disks maintenance when a drive becomes unavailable and its attributes can't be read anymore from the RAID controller.
It also helps to standardize the extended disk attributes across the different manufacturers.
As the disk physical identifers were not available under the correct format (hexadecimal format using the `xml` output as opposed as `X:Y:Z` format using the default `list` format), the command line parser has been refactored to read the `list` format, rather than `xml` one in the `omreport` raid controller parser.
As the custom fields have to be created prior being able to register the disks extended attributes, this …
> Added disks extended attributes

- netbox_agent/lshw.py
- setup.py
Some interfaces do not have device (logical) name (eth0, for instance), such as not connected network mezzanine cards in blade servers.
In such situations, the card will be named `unknown[0-9]`.
> Unnamed network interfaces.

- netbox_agent/network.py
This patch fixes a mismatch between the way network interfaces are looked for from network cards, and the way they are created:
- If a network card has a NAC address, it used in the search criteria to
find the network interface
- When creating virtual interfaces, the MAC address is not specified in
the creation parameters
This raises an exception when a virtual card has a MAC address:
- The virtual interface has been created without MAC address
- But the network card has one, so the interface is looked for using it
- The network interface is not found, so it's created
- An error is risen because an interface with the same name already
exists
This patch sets the MAC address on the interface if it exists, no matter if it is virtual or not.
> Fixed virtual network cards creation

- netbox_agent/raid/hp.py
- netbox_agent/raid/omreport.py
- netbox_agent/raid/storcli.py
The function parsing the RAID logical volumes in the HP module did not manage the case where disks were set in JBOD mode, thus having no RAID array set.
This patch fixes this by checking if arrays are defined on pdisks before parsing the logical disks.
Also added returncode read when executing the RAID related commands to raise a more precise error.
> Fixed HP raid parser when disks are in JBOD

- netbox_agent/config.py
- netbox_agent/server.py
Add a param `--preserve-tags` to keep all tags, default behavior is to override tags.
> fix(#212): prevent server tags to be override by default

- netbox_agent/config.py
- netbox_agent/misc.py
- netbox_agent/server.py
- netbox_agent/virtualmachine.py
https://github.com/Solvik/netbox-agent/pull/215 with auto detect device platform / os added
> Added platform to the config with auto-detect as fallback

- README.md
Unify the notation of netbox_agent.yaml in the README.
I was confused by the following two yml and yaml patterns in the README.
```
```
```
```
I checked and the `netbox_agent.yaml.example` file exists in the repository, so I assume `yaml` is correct.
> Fix netbox_agent.yml to netbox_agent.yaml

- netbox_agent/raid/hp.py
We have a box with multiple raidcards and we still dont use the second, thats how we found this "bug"
> Bug: if HP raidcard have no discs

- netbox_agent/inventory.py
Dvd-ram write are consider as disk and try to be parse,
We should ignore them. I'm not sure its necessary to create a dedicated function for this, I will consider them as "virtual disk".
Also fix size fallback to 0.
> Inventory disk issue

- netbox_agent/raid/hp.py
```
DEBUG:urllib3.connectionpool:https://netbox.local:443 "GET /api/dcim/inventory-items/?device_id=9&tag=hw-disk&limit=0 HTTP/1.1" 200 52
('A cache backup failure has occurred. Please execute the "reenablecache" '
'command')
File "/usr/bin/netbox_agent", line 33, in <module>
sys.exit(load_entry_point('netbox-agent==0.7.1', 'console_scripts', 'netbox_agent')())
File "/opt/netbox-agent/lib/python3.6/site-packages/netbox_agent/cli.py", line 50, in main
File "/opt/netbox-agent/lib/python3.6/site-packages/netbox_agent/cli.py", line 43, in run
server.netbox_create_or_update(config)
File "/opt/netbox-agent/lib/python3.6/site-packages/netbox_agent/server.py", line 417, in netbox_create_or_update
self.inventory.create_or_update()
File …
```
> fix: HP inventory crash is some warnings

- netbox_agent/inventory.py
dvdrom dont have serial number, we fallback on a 'unknown' value now to prevent crash
> fix: dvdrom inventory crash

- netbox_agent/raid/storcli.py
When there is a lot of data return by storcli due to a lot of disk, the inventory was in deadlock Its a known problem, see:
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait
> fix: deadlock storcli inventory

- netbox_agent/raid/hp.py
to prevent false positive like `/data/cache/temp` for eg
> fix: hp controller inventory, add space in ignore_patterns

- netbox_agent/config.py
- netbox_agent/network.py
This PR makes IPMI interface creation optional, for scenarios where the `ipmi lan print` command doesn't return correct information.
> Make IPMI information gathering optional

- netbox_agent/lshw.py
Fixes #227  
Newer versions of LSHW can return multiple logical names. This is parsed as an array. Netbox-agent assumes that the name is always a string, hence the failure. 
This patch checks if the logical name output is a string or an array. If it is an array each logical name is added to the unknown interfaces list.
> fix: lshw crashes due to duplicate logical name #227

- netbox_agent/network.py
- requirements.txt
> netifaces2

- netbox_agent/__init__.py
Removed in Python 3.12. Use importlib instead
> Replaced deprecated module pkg_resources

- netbox_agent/network.py
This avoids an issue where the requested URI is too long when many interfaces are present
> feat(network): Batch requests when filtering on interfaces

- netbox_agent/config.py
- netbox_agent/server.py
Add an alternative method to resolve server serial number and name conflicts which updates the serial number of the existing server object in Netbox with the same name as the current server.
This option addresses the situation as --purge-old-devices but does not delete the existing server object in Netbox.
This option is useful if a server is replaced by another with the same name and it is desired to keep all its properties that have been added manually in Netbox, so the existing server object will be updated with the serial number of the new server.
> New command line option --update-old-devices to update the serial number of old servers

- netbox_agent/lldp.py
- tests/fixtures/lldp/223.txt
- tests/network.py
```
lldp.eth0.vlan.vlan-id=300
lldp.eth0.vlan.pvid=yes
lldp.eth0.vlan=VLAN300
```
```
Version: lldpd 1.0.11
```
```
File "/root/.local/bin/netbox_agent", line 8, in <module>
sys.exit(main())
File "/root/.local/lib/python3.10/site-packages/netbox_agent/cli.py", line 44, in main
File "/root/.local/lib/python3.10/site-packages/netbox_agent/cli.py", line 39, in run
server.netbox_create_or_update(config)
File "/root/.local/lib/python3.10/site-packages/netbox_agent/server.py", line 292, in netbox_create_or_update
self.network.create_or_update_netbox_network_cards()
File "/root/.local/lib/python3.10/site-packages/netbox_agent/network.py", line 417, in create_or_update_netbox_network_cards
ret, interface = self.reset_vlan_on_interface(nic, …
```
> Fix KeyError: 'pvid' in lldp.py

- netbox_agent/hypervisor.py
Use a command or script to get the names of VMs from a hypervisor.
https://github.com/Solvik/netbox-agent/issues/336
> fix virtual guests command

- .github/workflows/tests.yml
Avoids unexpected CI failures when a new ruff version is released
> Get ruff version from pyproject for CI

- netbox_agent/config.py
- netbox_agent/ethtool.py
- netbox_agent/ipmi.py
- netbox_agent/network.py
- Add 2 new options (defaults unchanged):
- primary MAC: use either the permanent or temporary MAC address
- network identifier: currently netbox-agent lookups NICs by their name + MAC (if available) to know which API object to update. This means you can't update either of these fields and lose metadata if one of these fields changes. Now it is configurable to be either device name or MAC (using the primary MAC from previous option)
New features:
- Update MAC address, if it is not used as the device identifier (Fix #166)
- Update interface name, if it is not used as the device identifier
- Netbox 4.2 compatibility (multiple / primary MAC address). Currently only one MAC will be set but we will expand this in the future
- Disable NICs if their link is known to be down
- Set speed & duplex …
> Network interface improvements

- netbox_agent/network.py
These max_speed of 2500Mbps and 5000Mbps are BaseT only as far as I can tell so I didn't bother to check the port type, but I can add that in if desired
There are 2.5GBase-SR SFP transceivers (not sure if these are part of any kind of standard) but that doesn't seem to be an option in netbox and SFP ports even when capable of 2.5G get reported as max_speed 1000Mbps as far as I can tell
> Add support for 2.5GBASE-T and 5GBASE-T interface types

- netbox_agent/misc.py
Fallback to platform names with less info
Fix #369
> Handle os-release without version or codename
